### ISSUE TITLE
add license?

### ISSUE THREAD

**Issue by hanwen** [alfonsosanchezbeato/ptrace-redirect#2]
It would be nice to add a license to this example, so people can copy & paste it with assurance. Maybe add an Apache2 or MIT license header?

thanks!

**Comment by alfonsosanchezbeato** [comment]
Makes sense. I've added a BSD type license: https://github.com/alfonsosanchezbeato/ptrace-redirect/blob/master/COPYING

**Comment by hanwen** [comment]
thanks!
